"""Double Quant — quantum computing for quantitative finance."""

from double_quant.algorithm.hhl import HHLSolver
from double_quant.algorithm.circuit import (
    CircuitVisualization,
    CircuitVisualizationError,
    ComputationProcessVisualization,
    StateEvolutionStep,
    StateEvolutionVisualization,
    visualize_quantum_circuit,
    visualize_quantum_computation_process,
    visualize_state_evolution,
)
from double_quant.algorithm.qubo import (
    NumPyMinimumEigensolverSolver,
    QAOASolver,
    QUBOSolver,
    QUBOSolverResult,
    SamplingVQESolver,
)
from double_quant.algorithm.shapley import (
    BinaryEnumerationCalculator,
    PermutationEnumerationCalculator,
    PermutationMCCalculator,
    QAEOptions,
    QuantumShapleyCalculator,
    ShapleyCalculator,
)
from double_quant.application import RiskAttributor
from double_quant.common import IsingProblem, QUBOProblem
from double_quant.data.source import (
    AKShareSource,
    PandasDataReaderSource,
    PriceSource,
    StooqSource,
    YFinanceSource,
)
from double_quant.data.transform import (
    to_covariance,
    to_expected_returns,
    to_log_returns,
)
from double_quant.programming import (
    BinaryOptimizationOperator,
    DecisionProblem,
    DecisionProgram,
    EuropeanCallPriceMeasure,
    ExpectedShortfallOperator,
    ExpectedShortfallMeasure,
    FinancialProblem,
    FinancialProgram,
    LinearSystemSolveOperator,
    MeasureFunction,
    OperatorResult,
    OperatorSpec,
    QuantumFinancialOperatorLibrary,
    ResourceProfile,
    RiskAttributionOperator,
    RiskAttributionSoftwareTemplate,
    ShapleyRiskContributionMeasure,
    TemplateResult,
    TemplateStep,
    ValuationProblem,
    ValuationProgram,
    default_operator_library,
    default_software_templates,
    dot,
    matmul,
    mean,
    quad_form,
    square,
    sum_,
)

__all__ = [
    "PriceSource",
    "YFinanceSource",
    "AKShareSource",
    "PandasDataReaderSource",
    "StooqSource",
    "to_log_returns",
    "to_covariance",
    "to_expected_returns",
    "HHLSolver",
    "CircuitVisualization",
    "CircuitVisualizationError",
    "ComputationProcessVisualization",
    "StateEvolutionStep",
    "StateEvolutionVisualization",
    "visualize_quantum_circuit",
    "visualize_quantum_computation_process",
    "visualize_state_evolution",
    "QUBOProblem",
    "IsingProblem",
    "ShapleyCalculator",
    "BinaryEnumerationCalculator",
    "PermutationEnumerationCalculator",
    "PermutationMCCalculator",
    "QuantumShapleyCalculator",
    "QAEOptions",
    "QUBOSolver",
    "QUBOSolverResult",
    "NumPyMinimumEigensolverSolver",
    "QAOASolver",
    "SamplingVQESolver",
    "RiskAttributor",
    "FinancialProgram",
    "FinancialProblem",
    "DecisionProgram",
    "DecisionProblem",
    "ValuationProgram",
    "ValuationProblem",
    "MeasureFunction",
    "ExpectedShortfallMeasure",
    "ShapleyRiskContributionMeasure",
    "EuropeanCallPriceMeasure",
    "OperatorSpec",
    "ResourceProfile",
    "OperatorResult",
    "QuantumFinancialOperatorLibrary",
    "ExpectedShortfallOperator",
    "LinearSystemSolveOperator",
    "BinaryOptimizationOperator",
    "RiskAttributionOperator",
    "TemplateStep",
    "TemplateResult",
    "RiskAttributionSoftwareTemplate",
    "default_operator_library",
    "default_software_templates",
    "sum_",
    "dot",
    "quad_form",
    "matmul",
    "mean",
    "square",
]
