[project]
name = "double-quant"
version = "0.1.0"
description = "Quantum quantitive finance"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.8",
    "pandas>=3.0.0",
    "pylatexenc>=2.10",
    "qiskit>=2.2.3",
    "qiskit-aer>=0.17.2",
    "scipy-stubs[scipy]>=1.16.3.0",
    "yfinance>=1.1.0",
]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/double_quant"]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "seaborn>=0.13.2",
]

[tool.pyright]
typeCheckingMode = "basic"

[tool.pytest.ini_options]
pythonpath = ["src"]

[[tool.uv.index]]
url = "https://mirrors.zju.edu.cn/pypi/web/simple"
default = true
